"use client";

import { useState } from "react";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <div className="flex min-h-screen relative z-10">
          {/* Sidebar - Width dynamically changes */}
          <Sidebar isOpen={isSidebarOpen} />
          {/* Main content */}
          <div className="flex-1 flex flex-col transition-all duration-300">
            {/* Navbar with toggle button */}
            <Navbar onToggleSidebar={() => setIsSidebarOpen(!isSidebarOpen)} />
            {/* Page content */}
            <div className="px-2 ">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
